import { Component, OnInit } from '@angular/core';
import { LevelServiceService } from 'src/app/shared/level-service.service';

@Component({
  selector: 'app-admin-misc-panel',
  templateUrl: './admin-misc-panel.component.html',
  styleUrls: ['./admin-misc-panel.component.css']
})
export class AdminMiscPanelComponent implements OnInit {

  bil_banner:string = '';

  constructor(
    public ill_service: LevelServiceService
  ) { }

  ngOnInit(): void {
  }

  async updateBanner() {
    //disable all banners

    let _bnr = await this.ill_service.pb.collection('banners').getFullList(200);
    let _bnrIDs = [];
    for(let i=0; i<_bnr.length; i++) {
      _bnrIDs[i] = _bnr[i]['id'];
      _bnr[i]['isPicked'] = false;
      await this.ill_service.pb.collection('banners').update(_bnrIDs[i], _bnr[i]);
    }

    let _newBanner = {
      name: 'autoGenerated',
      url: this.bil_banner,
      isPicked: true
    }
    await this.ill_service.pb.collection('banners').create(_newBanner);
  }

}
